blog/urls.py
from django.urls import path,re_path

from .views import *
from student_management_app.views import *

urlpatterns = [
    path('', Homeview,name='home'),
    path('article/<int:pk>/',Articledetails,name='article'),
    

   


    path('like_post/',LikeView,name='like_post'),
    path('dislike_post/',DisLikeView,name='dislike_post'),
    path('like_comment/',LikeCommentView,name='like_comment'),
    path('dislike_comment/',DisLikeCommentView,name='dislike_comment'),
    path('article/<int:pk>/remove/',DeletePost.as_view(),name='delete_post'),
    path('category/<str:cats>/',category_view,name='category'),
    path('search/', SearchView,name='search'),
    path('manage_category/',manage_category,name="manage_category"),
    path('add_post',add_post,name = "add_post"), 
    path('edit_post/<str:post_id>',edit_post,name = "edit_post"),
    path('edit_post_save', edit_post_save,name="edit_post_save"),
    path('delete_post/<int:pk>',DeletePost.as_view(),name = "delete_post"),
    path('manage_post',manage_post,name = "manage_post"),
    path('featured_articles/',Featured_view,name="featured_articles"),
    path('most_viewed_articles/',Most_view,name="most_viewed_articles"),
    path('latest_articles/',Latest_Post,name="latest_articles"),
    # path('trending_topic/',TrendingTopicView,name="trending_topic"),
    path('most_like_articles/',Most_Like_Post,name="most_like_articles"),
    path('add_new_comments/',AddComments,name="add_new_comments"),
    path('profile/<str:user>/',ProfileView,name="user_profile"),
]

student_management_app/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from blog.views import *
from student_management_app import views, HodViews, StaffViews, StudentViews
from django.conf import settings
from .views import * 
from .PrincipalView import *
from .HodViews import *

urlpatterns = [
    path('signup_principal',views.signup_principal,name="signup_principal"),
    path('signup_admin',views.signup_admin,name="signup_hod"),
    path('signup_student',views.signup_student,name="signup_student"),
    path('signup_staff',views.signup_staff,name="signup_staff"),
    path('do_principal_signup',views.do_principal_signup,name="do_principal_signup"),
    path('do_hod_signup',views.do_hod_signup,name="do_hod_signup"),
    path('do_staff_signup',views.do_staff_signup,name="do_staff_signup"),
    path('do_signup_student',views.do_signup_student,name="do_signup_student"),
    path('',views.ShowLoginPage,name="show_login"),
    path('logout_user', views.logout_user,name="logout_user"),
    path('doLogin',views.doLogin,name="do_login"),
    path('hod_home',HodViews.Hod_home,name="hod_home"),
    path('principal_home',principal_home,name="principal_home"),
    

    path('add_department/', add_department,name="add_department"),
    path('add_department_save', add_department_save,name="add_department_save"),
    path('edit_department/<str:dept_id>', edit_department,name="edit_department"),
    path('edit_department_save', edit_department_save,name="edit_department_save"),
    path('manage_department', manage_department,name="manage_department"),
    path('manage_staff', manage_staff,name="manage_staff"),
    path('edit_staff/<str:staff_id>', edit_staff,name="edit_staff"),
    path('edit_staff_save', edit_staff_save,name="edit_staff_save"),
    path('add_session_save', add_session_save,name="add_session_save"),
    path('manage_session', manage_session,name="manage_session"),
    path('check_email_exist', check_email_exist,name="check_email_exist"),
    path('check_username_exist', check_username_exist,name="check_username_exist"),
    path('staff_feedback_message', staff_feedback_message,name="staff_feedback_message"),
    path('staff_feedback_message_replied', staff_feedback_message_replied,name="staff_feedback_message_replied"),
    path('student_leave_view', student_leave_view,name="student_leave_view"),
    path('staff_leave_view', staff_leave_view,name="staff_leave_view"),
    path('staff_disapprove_leave/<str:leave_id>', staff_disapprove_leave,name="staff_disapprove_leave"),
    path('staff_approve_leave/<str:leave_id>', staff_approve_leave,name="staff_approve_leave"),
    path('edit_hod/<int:hod_id>', edit_hod,name="edit_hod"),
    path('edit_hod_save', edit_hod_save,name="edit_hod_save"),
    

    path('add_subject', HodViews.add_subject,name="add_subject"),
    path('add_subject_save', HodViews.add_subject_save,name="add_subject_save"),
    path('manage_student', HodViews.manage_student,name="manage_student"),
    path('manage_subject', HodViews.manage_subject,name="manage_subject"),
    path('edit_student/<str:student_id>', HodViews.edit_student,name="edit_student"),
    path('edit_student_save', HodViews.edit_student_save,name="edit_student_save"),
    path('edit_subject/<str:subject_id>', HodViews.edit_subject,name="edit_subject"),
    path('edit_subject_save', HodViews.edit_subject_save,name="edit_subject_save"),
    path('student_approve_leave/<str:leave_id>', student_approve_leave,name="student_approve_leave"),
    path('student_disapprove_leave/<str:leave_id>', student_disapprove_leave,name="student_disapprove_leave"),
    path('student_feedback_message', student_feedback_message,name="student_feedback_message"),
    path('student_feedback_message_replied', student_feedback_message_replied,name="student_feedback_message_replied"),
    path('admin_view_attendance', HodViews.admin_view_attendance,name="admin_view_attendance"),
    path('admin_get_attendance_dates', HodViews.admin_get_attendance_dates,name="admin_get_attendance_dates"),
    path('admin_get_attendance_student', HodViews.admin_get_attendance_student,name="admin_get_attendance_student"),
    
    path('delete/<str:type>/<int:id>',Delete,name='delete'),
    path('staff_home', StaffViews.staff_home, name="staff_home"),
    path('staff_take_attendance', StaffViews.staff_take_attendance, name="staff_take_attendance"),
    path('staff_update_attendance', StaffViews.staff_update_attendance, name="staff_update_attendance"),
    path('get_students', StaffViews.get_students, name="get_students"),
    path('get_attendance_dates', StaffViews.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student', StaffViews.get_attendance_student, name="get_attendance_student"),
    path('save_attendance_data', StaffViews.save_attendance_data, name="save_attendance_data"),
    path('save_updateattendance_data', StaffViews.save_updateattendance_data, name="save_updateattendance_data"),
    path('assignment_check', StaffViews.assignment_check, name="assignment_check"),
    path('get_students_assignment', StaffViews.get_students_assignment, name="get_students_assignment"),
    
    path('assignment_upload',StaffViews.Assignment_upload,name="assignment_upload"),
    path('apply_leave', apply_leave, name="apply_leave"),
    path('apply_leave_save', apply_leave_save, name="apply_leave_save"),
    path('feedback', feedback, name="feedback"),
    path('feedback_save', feedback_save, name="feedback_save"),
    path('staff_profile', StaffViews.staff_profile, name="staff_profile"),
    path('staff_profile_save', StaffViews.staff_profile_save, name="staff_profile_save"),


    path('student_home', StudentViews.student_home, name="student_home"),
    path('student_view_attendance', StudentViews.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post', StudentViews.student_view_attendance_post, name="student_view_attendance_post"),
    path('student_profile', StudentViews.student_profile, name="student_profile"),
    path('student_profile_save', StudentViews.student_profile_save, name="student_profile_save"),
    path('assignment_view',StudentViews.assignment_view,name="assignment_view"),
    path('assignment_submit/<int:id>',StudentViews.assignment_submit,name="assignment_submit"),
    path('assignment_save',StudentViews.assignment_save,name="assignment_save"),
    
]

students_management_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from students_management_project import settings
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/gettoken/',TokenObtainPairView.as_view(),name="gettoken"),
    # path('api/resfresh_token/',TokenRefreshView.as_view(),name="refresh_token"),
    path('api/auth/', include('rest_framework.urls')),
    path('users/',include('user.urls')),
    path('', include('blog.urls')),
    path('backend/',include('student_management_app.urls')),
    path('api/gettoken/',TokenObtainPairView.as_view(),name="gettoken"),
    path('api/refresh_token/',TokenRefreshView.as_view(),name="refresh_token"),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student_management_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from user.models import User
# Create your models here.
class SessionYearModel(models.Model):
    id=models.AutoField(primary_key=True)
    session_start_year=models.DateField()
    session_end_year=models.DateField()
    objects=models.Manager()


class Principal(models.Model):
    id=models.AutoField(primary_key=True)
    profile_pic = models.FileField()
    admin=models.OneToOneField(User,on_delete=models.CASCADE,related_name='principal')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()


class Department(models.Model):
    id=models.AutoField(primary_key=True)
    dept_name=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

class HOD(models.Model):
    id=models.AutoField(primary_key=True)
    profile_pic = models.FileField()
    dept_id=models.OneToOneField(Department,on_delete=models.CASCADE,related_name='hod_dept')
    admin=models.OneToOneField(User,on_delete=models.CASCADE,related_name='hod')
    address=models.TextField(default="ban")
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()
    @property
    def get_dept_name(self):
        return self.dept_id.dept_name

class Staffs(models.Model):
    id=models.AutoField(primary_key=True)
    profile_pic = models.FileField()
    dept_id=models.ForeignKey(Department,on_delete=models.CASCADE,related_name='staff_dept')
    admin=models.OneToOneField(User,on_delete=models.CASCADE,related_name="staff")
    address=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()
    @property
    def get_dept_name(self):
        return self.dept_id.dept_name




class Subjects(models.Model):
    id=models.AutoField(primary_key=True)
    subject_name=models.CharField(max_length=255)
    dept_id=models.ForeignKey(Department,on_delete=models.CASCADE)
    staff_id=models.ForeignKey(User,on_delete=models.CASCADE)
    session_year = models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()



class Students(models.Model):
    id=models.AutoField(primary_key=True)
    admin=models.OneToOneField(User,on_delete=models.CASCADE,related_name='student')
    gender=models.CharField(max_length=255)
    profile_pic = models.FileField()
    address=models.TextField()
    dept_id=models.ForeignKey(Department,on_delete=models.CASCADE,related_name='student_dept')
    session_year_id=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

    @property
    def get_dept_name(self):
        return self.dept_id.dept_name


class Assignment(models.Model):
    id=models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    subject_id = models.ForeignKey(Subjects,on_delete=models.CASCADE) 
    staff = models.ForeignKey(User,on_delete=models.CASCADE)
    upload_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()   
    assignment = models.FileField()
    objects = models.Manager()

    @property
    def check_deadline(self):
        return self.deadline.timestamp() >= timezone.now().timestamp()


class AssignmentReport(models.Model):
    id = models.AutoField(primary_key=True)
    assignment = models.ForeignKey(Assignment,on_delete=models.CASCADE)
    file = models.FileField()
    student = models.ForeignKey(User,on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()


class LeaveReport(models.Model):
    id=models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    leave_date=models.CharField(max_length=255)
    leave_message=models.TextField()
    leave_status=models.IntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()

  
class FeedBack(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.TextField()
    feedback_reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()



class Attendance(models.Model):
    id=models.AutoField(primary_key=True)
    subject_id=models.ForeignKey(Subjects,on_delete=models.DO_NOTHING)
    attendance_date=models.DateField()
    created_at=models.DateTimeField(auto_now_add=True)
    session_year_id=models.ForeignKey(SessionYearModel,on_delete=models.CASCADE)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

class AttendanceReport(models.Model):
    id=models.AutoField(primary_key=True)
    student_id=models.ForeignKey(Students,on_delete=models.DO_NOTHING)
    attendance_id=models.ForeignKey(Attendance,on_delete=models.CASCADE)
    status=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now_add=True)
    objects=models.Manager()


@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        if instance.user_type==0:
            Principal.objects.create(admin=instance,profile_pic="")
        elif instance.user_type==1:
            HOD.objects.create(admin=instance,profile_pic="",dept_id=None)
        elif instance.user_type==2:
            Staffs.objects.create(admin=instance,dept_id=None,address="",profile_pic="")
        elif instance.user_type==3:
            Students.objects.create(admin=instance,dept_id=None,session_year_id=None,address="",profile_pic="",gender="")

student_management_app/templates/staff_template/add_tag.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Add Tag
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Tag</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{% url 'add_tag_save_for_staff' %}" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Tag Name </label>
                    <input type="text" class="form-control" name="tag" placeholder="Enter Tag">
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Add Tag</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/staff_template/assignment_upload.html
{% extends 'base_template.html' %}
{% block page_title %}
Add Assignment
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add Assignment</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{% url 'assignment_upload' %}" enctype="multipart/form-data" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Title </label>
                    <input type="text" class="form-control" name="title" placeholder="Enter assignment name">
                  </div>
                   <div class="form-group">
                    <label>Subjects </label>
                    <select class="form-control" name="subject_id">
                        {% for subject in subjects %}
                          <option value="{{ subject.id }}">{{ subject.subject_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                  
                  <div class="form-group">
                    <label>Assignment</label>
                    <input type="file" name="assignment" class="form-control" enctype="multipart/form-data">
                  </div>

                  <div class="form-group">
                    <label>Deadline</label>
                    <input type="datetime-local" class="form-control" name="deadline">
                  </div>

                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block">Upload Assignment</button>
                </div>
              </form>
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/staff_template/assignment_view.html
{% extends 'base_template.html' %}
{% block page_title %}
Assignment Check
{% endblock page_title %}
{% block main_content %}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Assignment Check</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                   <div class="form-group">
                    <label>Subject </label>
                    <select class="form-control" name="subject" id="subject">
                        {% for subject in subjects %}
                          <option value="{{ subject.id }}">{{ subject.subject_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Assignments</label>
                    <select class="form-control" name="assignment" id="assignment">
                        {% for assignment in assignments %}
                          <option value="{{ assignment.id }}">{{assignment.title }}</option>
                        {% endfor %}
                    </select>
                  </div>
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="button" class="btn btn-primary btn-block" id="fetch_student_assignment">Fetch Students Assignment</button>
                </div>
            </div>
            <!-- /.card -->
          </div>
          </div>
          <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Assignment Details</h3>
                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                  <th>Student ID</th>
                                  <th>Student Name</th>
                                  <th>Submited At </th>
                                  <th>View Assignment</th>
                                  <th>Download Assignment</th>
                                </tr>
                            </thead>
                            <tbody id='add_assignment'>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#fetch_student_assignment").click(function(){
            var subject=$("#subject").val()
            var assignment=$("#assignment").val()

            $.ajax({
                url:'{% url 'get_students_assignment' %}',
                type:'POST',
                data:{subject:subject,assignment:assignment},
            })
            .done(function(response){
                var json_data=JSON.parse(response);
                console.log(json_data);
                var div_data = "";
                for(key in json_data){
                    div_data += `<tr>
                      <td>`+json_data[key]['id']+`</td>
                      <td>`+json_data[key]['name']+`</td>
                      <td>`+json_data[key]['time']+`</td>
                      <td><a href=`+json_data[key]['file']+` class="btn btn-outline-primary">View Assignment</a></td>
                      <td><a href=`+json_data[key]['file']+` download class="btn btn-outline-success">Download Assignment</a></td> 
                    </tr>`
                }
                $("#add_assignment").html(div_data);

            })
            .fail(function(){
                alert("Error in Fetching Student assignment")
            })
        })
    })
</script>
{% endblock custom_js %}

student_management_app/templates/staff_template/edit_post.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Edit Post
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
          <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Post</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                {% url 'edit_post_save_for_staff' as action_path %}
                {% include 'staff_template/form_template.html' with messages=messages form=form action_path=action_path button_text="Edit Post" %}
            </div>
            <!-- /.card -->



          </div>
          </div>
      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}

student_management_app/templates/staff_template/edit_student_result.html
{% extends 'staff_template/base_template.html' %}
{% block page_title %}
Edit Results
{% endblock page_title %}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
                    <div class="row">
              <div class="col-md-12">
            <!-- general form elements -->
             <form action="{% url 'edit_student_result' %}" method="post">
                 {% csrf_token %}
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Results</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                <div class="card-body">
                    {{ form }}
                   <div class="form-group">
                      {% if messages %}
                        {% for message in messages %}
                        {% if message.tags == 'error' %}
                        <div class="alert alert-danger" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% if message.tags == 'success' %}
                        <div class="alert alert-success" style="margin-top:10px">{{ message }}</div>
                        {% endif %}
                        {% endfor %}
                      {% endif %}
                    </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary btn-block" id="fetch_student">Update Result</button>
                </div>
            </div>
             </form>
            <!-- /.card -->



          </div>
          </div>

      </div>
    </section>
    <!-- /.content -->
{% endblock main_content %}
{% block custom_js %}
<script>
    $(document).ready(function(){
        $("#id_session_ids").change(function(){
            fetchStudents();
        });
        $("#id_subject_id").change(function(){
            fetchStudents();
        });

        $("#id_student_ids").change(function(){
            fetch_result_student();
        })

        function fetchStudents(){
            var session_year=$("#id_session_ids").val()
            var subject=$("#id_subject_id").val()

            $.ajax({
                url:'{% url 'get_students' %}',
                type:'POST',
                data:{subject:subject,session_year:session_year},
            })
            .done(function(response){
                var json_data=JSON.parse(response);
                console.log(json_data)
                var div_data="";
                for(key in json_data)
                {
                    div_data+="<option value='"+json_data[key]['id']+"'>ID : "+json_data[key]['id']+" : "+json_data[key]['name']+"</option>";
                }

                $("#id_student_ids").html(div_data);

            })
            .fail(function(){
                alert("Error in Fetching Student")
            });
        }

        function fetch_result_student(){
            var id_student_ids=$("#id_student_ids").val()
            var subject=$("#id_subject_id").val()

            $.ajax({
                url:'{% url 'fetch_result_student' %}',
                type:'POST',
                data:{subject_id:subject,student_id:id_student_ids},
            })
            .done(function(response){
                if(response=="False"){
                    alert("Result Not Found")
                }
                else{
                    var json_data=JSON.parse(response);
                    $("#id_assignment_marks").val(json_data['assign_marks'])
                    $("#id_exam_marks").val(json_data['exam_marks'])
                }

            })
            .fail(function(){
                alert("Error in Fetching Student")
            });
        }
    })
</script>
{% endblock custom_js %}

student_management_app/templates/staff_template/footer.html
 <footer class="main-footer">
    <strong>Copyright &copy; 2020-2021 <a href="https://supercoders.in">Ashis.in</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0
    </div>
  </footer>